# Generated by Django 2.1.1 on 2019-02-23 10:26

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190223_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
