# Generated by Django 2.1.1 on 2019-02-23 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20190224_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_like_users',
            field=models.ManyToManyField(blank=True, related_name='blog_like_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fan_users',
            field=models.ManyToManyField(blank=True, related_name='fan_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follow_users',
            field=models.ManyToManyField(blank=True, related_name='follow_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_like_blogs',
            field=models.ManyToManyField(blank=True, related_name='user_like_blogs', to='blogs.Blog'),
        ),
    ]
