# Generated by Django 2.1.1 on 2019-02-24 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20190224_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='replycomment',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='comment_reply_comments',
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='comment_like_users',
            field=models.ManyToManyField(blank=True, related_name='comment_like_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='reply_comment_like_users',
            field=models.ManyToManyField(blank=True, related_name='reply_comment_like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
