# Generated by Django 2.1.1 on 2019-02-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20190224_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='text',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='text',
            field=models.TextField(max_length=512),
        ),
    ]
