# Generated by Django 2.1.1 on 2019-02-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20190224_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='reply_comments',
            field=models.ManyToManyField(blank=True, related_name='reply_comments', to='blogs.ReplyComment'),
        ),
    ]
